### ISSUE TITLE
Making ace perms optional

### ISSUE THREAD

**Issue by radiusdevelop** [JellyJamm/fivemgasmask#1]
Hi, so I have stumbled upon your script and it's amazing but there should honestly be a way to use this without ace perms.

**Comment by JellyJamm** [comment]
ACE Permissions are, by default, built into every FiveM server. If you don't want it to be restricted, simply add this line in your server.cfg **after** the script is started.

```add_ace builtin.everyone perms.gasmask```

This will assign the ace permission to every single person. No restrictions necessary :)
